### ISSUE TITLE
https://github.com/meet-minimalist/TinyImageNet-Benchmarks.git

### ISSUE THREAD

**Issue by deepgreenAntennas** [meet-minimalist/TinyImageNet-Benchmarks#4]

**Comment by meet-minimalist** [comment]
What is the issue here?

**Comment by deepgreenAntennas** [comment]
Your AirPod pro will connect leftside and there will be lag connecting
right earbud @StereoUI

**Comment by meet-minimalist** [comment]
Closing the issue as it is not related to the repo.
